pre_processing_params:
  statistical_outlier_removal:
    nb_neighbors: 78  # small: too sensitive to noise, large: too conservative
    std_ratio: 3.4  # small: would remove too much, large: would fail to capture outliers
  radius_outlier_removal:
    radius: 2  # small: too sensitive to noise, large: too conservative
    min_neighbors: 4  # small: would fail to capture outliers, large: would remove too much

noise_filtering_params:
  min_range: 3  # smallest LiDAR PCD range (in m)
  max_range: 240  # largest LiDAR PCD range (in m)

ground_plane_filtering_params:
  min_points_to_fit: 3
  distance_threshold: 0.1
  num_iterations: 1000
  ransac_frequency: 5
  seed_sampling_method: "horizontal_angle" # random, surface_normals, horizontal_angle
  surface_normal_sampling_params:
    radius: 0.1
    max_nn: 50
    selection_threshold: 0.1
  horizontal_sampling_params:
    min_angle: -0.523599
    max_angle: 0.523599
  random_sampling_params:
    num_samples: 100